refacto: Continue to make dashboard strict compatible
betagouv/signalement-app pull request #515
Opened 2021-01-20 08:14 UTC by alexandreannic

2021-01-22 07:48 UTC, jrivals requested changes
Attention au commit du fichier src/environments/environment.prod.ts

Beaucoup de modif, à bien tester sur démo avant MEP

2021-01-22 07:48 UTC, jrivals commented on src/environments/environment.prod.ts
> -  apiReportBaseUrl: '${API_BASE_URL}',
Attention

2021-01-22 09:55 UTC, jrivals approved these changes

2021-01-25 17:19 UTC, alexandreannic commented
J'ai fait le tour des pages modifiées. Tout semble bien fonctionner.

2021-01-26 08:55 UTC, merged